Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.hostname = "ubuntu"
    config.vm.define "UbuntuBox"

#    config.ssh.username = 'root'
#    config.ssh.password = 'vagrant'
#    config.ssh.insert_key = 'true'
    
    config.vm.network "private_network", ip: "172.30.1.5"
    
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 2
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    end
end